{
    "name": "AreaMobs",
    "author": "hachkingtohach1",
    "api": "4.0.0",
    "version": "1.0.1",
    "main": "hachkingtohach1\\AreaMobs\\AreaMobs",
    "website": "http://devilcry.sytes.net/dashboard/",
    "description": "Plugin AreaMobs for pocketmine_pmmp",
    "permissions": {},
    "commands":{}
}