{
    "name": "CoinsAPI",
    "author": "hachkingtohach1",
    "api": [
        "3.0.0", "3.14.0", "3.14.1", "3.14.2", "3.19.0", 
    ],
    "version": "1.0",
    "main": "hachkingtohach1\\CoinsAPI\\CoinsAPI",
    "website": "https://watchshit.weebly.com/",
    "description": "Plugin CoinsAPI, software pocketmine_pmmp",
}