{
    "name": "CraftBook",
    "author": "hachkingtohach1",
    "api": "3.19.3", 
    "version": "1.0.0",
    "main": "hachkingtohach1\\CraftBook\\CraftBook",
    "website": "http://devilcry.sytes.net/dashboard/",
    "description": "Plugin CraftBook for pocketmine_pmmp",
    "commands":{ 
        "craftbook":{
            "description": "Plugin CraftBook for pocketmine_pmmp"
        },
        "cbc":{
            "description": "Plugin CraftBook for pocketmine_pmmp"
        }
    }
}