{
    "name": "EnderSword",
    "author": "hachkingtohach1",
    "api": "3.19.3", 
    "version": "2.9",
    "main": "hachkingtohach1\\EnderSword\\EnderSword",
    "website": "http://devilcry.sytes.net/dashboard/",
    "description": "Plugin EnderSword for pocketmine_pmmp",
    "commands":{ 
        "getes":{
            "description": "Plugin EnderSword for pocketmine_pmmp"
        }
    }
}