name: Fly
main: Fly\Main
author: Ghast Noob
description: "Bật Hoặc Tắt Bay Khi Ở Chế Độ Sinh Tồn"
version: 1.0.0
api: 2.0.0

commands:
 fly:
  usage: "§b❖§a/fly Để Bật Hoặc Tắt Chế Độ Bay§b❖"
  description: "Bật Hoặc Tắt Bay Khi Ở Chế Độ Sinh Tồn"
permissions:
  fly.me:
    default: op
    description: "Bật Hoặc Tắt Bay Khi Ở Chế Độ Sinh Tồn"
