{
    "name": "Dungeons",
    "author": "hachkingtohach1",
    "api": "3.19.3", 
    "version": "1.0.0",
    "main": "hachkingtohach1\\Dungeons\\Dungeons",
    "website": "http://devilcry.sytes.net/dashboard/",
    "description": "Plugin Dungeons for pocketmine_pmmp",
    "commands":{ 
        "dungeons":{
            "description": "Plugin Dungeons for pocketmine_pmmp"
        }
    }
}