--- 
MESSAGE_YOU_ENOGHT: "You have crafted it successfully!"
MESSAGE_YOU_NOT_ENOGHT: "You don't have enough material to craft this item"

TITLE_MENU: "CraftBook"

CRAFT_ITEM: 
    ID: 35
    META: 5
    COUNT: 1
    NAME: "Craft"

NEXT_PAGE_ITEM: 
    ID: 262
    META: 0
    COUNT: 1
    NAME: "Next Page"
    LORE: ["%page/%maxpage", "Click to next"]
    
NEXT_REVERSE_ITEM: 
    ID: 262
    META: 0
    COUNT: 1
    NAME: "Reverse Page"
    LORE: ["%page/%maxpage", "Click to reverse"]
...
