{
    "name": "TrumThe",
    "author": "hachkingtohach1",
    "api": "3.19.3", 
    "version": "1.0.0",
    "main": "hachkingtohach1\\TrumThe\\TrumThe",
    "website": "http://devilcry.sytes.net/dashboard/",
    "description": "Plugin TrumThe for pocketmine_pmmp",
    "commands":{ 
        "napthe":{
            "description": "Plugin Napthe for pocketmine_pmmp"
        },
    }
}
