{
    "name": "Market",
    "author": "hachkingtohach1",
    "api": "4.0.0",
    "version": "1.0.1",
    "main": "hachkingtohach1\\Market\\Market",
    "website": "http://devilcry.sytes.net/dashboard/",
    "description": "Plugin Market for pocketmine_pmmp",
    "permissions": {
        "market.command": {
            "description": "Permission to use the Market command",
            "default": true
        }
    },
    "commands":{ 
        "mk":{
            "description": "Plugin Market for pocketmine_pmmp",
            "permission": "market.command"
        },
         "mks":{
            "description": "Plugin Market for pocketmine_pmmp",
            "permission": "market.command"
        },
         "mkm":{
            "description": "Plugin Market for pocketmine_pmmp",
            "permission": "market.command"
        }
    }
}