---
API_KEY: "WLXaFxOFpIszFCEl8Nc9dAe6Nl50nle1iz"

command:
  usage: vote # /vote in game
  description: "Allows to have his recompense of vote"

message_has_not_voted:
  enable: true
  message: "§cBạn chưa bầu chọn cho server!"

message_has_already_voted:
  enable: true
  message: "§eBạn đã bàu chọn cho server hôm nay rồi!"

message_player:
  enable: true
  message:  "§eCảm ơn bạn đã bầu chọn cho server!"

message_everyone:
  enable: true
  message: "§a{player}§e đã bầu chọn cho server!"

# items | commands
reward_type: items

# rewards item
rewards_items:
  - "310#0#1#Vote Reward" # id#meta#amount#customName
  - "311#0#1#Vote Reward" # id#meta#amount#customName
  - "312#0#1#Vote Reward" # id#meta#amount#customName
  - "313#0#1#Vote Reward" # id#meta#amount#customName
  - "279#0#1#Vote Reward" # id#meta#amount#customName
  - "293#0#1#Vote Reward" # id#meta#amount#customName
  - "278#0#1#Vote Reward" # id#meta#amount#customName
  - "277#0#1#Vote Reward" # id#meta#amount#customName
  - "322#0#10#Vote Reward" # id#meta#amount#customName
  - "353#0#10#Vote Reward" # id#meta#amount#customName
  - "362#0#10#Vote Reward" # id#meta#amount#customName
  - "130#0#1#§e§1§c§6Premium Case" # id#meta#amount#customName

# rewards commands
rewards_commands:
...
