---
plugin-name: essentalsTp+
sqlite-dbname: essentials_tp
tpa-here-cooldown: "30"
tp-home-cooldown: "5"
tp-warp-cooldown: "5"
tp-spawn-cooldown: "5"
MOTD: Chào mừng!
wild-MaxX: "300"
wild-MaxY: "300"
bed-sets-home: "true"
Lang_invalid_usage: 'Sử dụng không hợp lệ:'
Lang_command_only_use_ingame: Lệnh này chỉ có thể sử dụng trong trò chơi.
Lang_no_permissions: '[EssentialsTP] Không cho phép.'
Lang_teleport_home: §f Đã dịch chuyển về nhà.
Lang_teleport_spawn: §f Đã dịch chuyển về spawn.
Lang_teleport_wild: §f Đã dịch chuyển ngẫu nhiên.
Lang_teleport_death: §f Đã dịch chuyển về chỗ chết.
Lang_no_spawn_set: §f Đã dịch chuyển về world spawn.
Lang_teleport_spawn_original: §f Đã dịch chuyển về spawn.
Lang_spawn_set: §f Đã đặt spawn.
Lang_your_homes: '§f Nhà của bạn:'
Lang_no_home_set: §f Bạn không có nhà nào.
Lang_no_home_name: §f Bạn không có nhà nào tên như thế.
Lang_home_set: §f Đã đặt nhà
Lang_home_delete_1: '§f Tên nhà:'
Lang_home_delete_2: đã bị xóa bỏ.
Lang_no_teleport_self: §f Không thể dịch chuyển về nơi chính mình.
Lang_player_not_online: §f Người chơi không Online.
Lang_sent_request_you: gửi yêu cầu dịch chuyển tới bạn.
Lang_sent_request_them: đã gửi yêu cầu tới bạn, để dịch chuyển đến họ.
Lang_accept_request: để đồng ý lời mời.
Lang_decline_request: để từ chối lời mời.
Lang_request_expire_1: Yêu cầu này chỉ tồn tại trong
Lang_request_expire_2: giây
Lang_request_expire_3: trước khi hết hạn.
Lang_type: Type
Lang_no_active_request: §f Lời mời đã hết hạn.
Lang_warps: §a Các Warps:§r
Lang_no_warps: §f Server không có warp nào.
Lang_no_warp_listed: §f Không có warp nào tên như vậy.
Lang_warp_set: §f Warp đặt là
Lang_warp_to: §f Bạn đã được dịch chuyển đến
Lang_warp_delete_1: '§f Warp '
Lang_warp_delete_2: đã bị xóa bỏ.
Lang_no_warps_name: §f Không có Warps nào tên như vậy.
Land_chunk_not_loaded: §f Không thể dịch chuyển.
Lang_action_cooldown: §f Hành động đã hết hạn.
Lang_no_death: §f Chết !
...
