name: xyz
main: GN\xyz\xyz
version: 1.0.1
api: [1.0.0]

load: POSTWORLD
author: Ghast Noob
description:  Cho Phép Người Chơi Xem Tọa Độ Nơi Mình Đang Đứng
commands:
 xyz:
  description: Returns Player Coordinates
  usage: "§a❖§cX§eY§dZ§a❖§b Ghi /xyz Để Xem Tọa Độ Bạn Đang Đứng"
  permission: xyz.command.xyz