
# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# PureChat version string
# - string
version: "1.4.10-7"

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags
# {display_name} Get the player's username.
# {msg} Get the player's message.
# {prefix} Get PurePerms Prefix of the rank.
# {suffix} Get the PurePerms Suffix of the rank.
# {world} Get the PurePerms world the player is in.

groups:
  Guest:
    chat: '&7{display_name} &f{msg}'
    nametag: '&7{display_name}'
    worlds: []
  Vip:
    chat: '§l§d✧§aVIP§r§l§d✧ §r§a{display_name} §8➽ &f{msg}'
    nametag: '§l§d✧§aVIP§r§l§d✧ §r§a{display_name}'
    worlds: []
  Vip+:
    chat: '§l§d✧§aVIP§c+§r§l§d✧ §r§a{display_name} §8➽ &f{msg}'
    nametag: '§l§d✧§aVIP§c+§r§l§d✧ §r§a{display_name}'
    worlds: []
  Vip++:
    chat: '§l§d✧§6VIP§9++§r§l§d✧ §r§6{display_name} §8➽ &f{msg}'
    nametag: '§l§d✧§6VIP§9++§r§l§d✧ §r§6{display_name}'
    worlds: []
  Admin:
    chat: '§7[§c§lAdmin§r§7] §r§c{display_name} §8➽ &f{msg}'
    nametag: '§7[§c§lAdmin§r§7] §r§c{display_name}'
    worlds: []
  Owner:
    chat: '§7[§d§lOwner§r§7] §r§f{display_name} §8➽ &b{msg}'
    nametag: '§7[§d§lOwner§r§7] §r§f{display_name}'
    worlds: []
  OP:
    chat: '&d[OP]  {display_name} &f{msg}'
    nametag: '&d[OP] {display_name}'
    worlds: []
...
