--- 
MESSAGE_JOIN: "> You have joined the game!"
MESSAGE_FULL: "> Game is full!"
MESSAGE_INGAME: "> You had already in-game!"
MESSAGE_INQUEUE: "> You are in the queue!"
MESSAGE_FOUND_ROOM: "> You have successfully found an empty room"
...
