{
    "name": "FarmingCrystal",
    "author": "hachkingtohach1",
    "api": [
        "3.0.0", "3.14.0", "3.14.1", "3.14.2", "3.19.0", "3.20.0"
    ],
    "version": "1.0.0",
    "main": "hachkingtohach1\\FarmingCrystal\\FarmingCrystal",
    "website": "https://watchshit.weebly.com/",
    "description": "Plugin FarmingCrystal, software pocketmine_pmmp"
}