---
ScoreBoardType: "public"
    
ScoreBoardPublic:                      
    broad:
        title: "§l§eSKYBLOCK"    
        score:    
            - "§7%whatday §8plati09M"
            - "§e"
            - "§cSự kiện: %event"
            - "§fRank: §a%rank"
            - "§f"
            - "§fCoins: §6%getmoney"
            - "§fGems: §2%getgems"
            - "§b"
            - "§aQuest: §f%quest §b%processquest°/ₒ"
            - "§7"
            - "§bKích cỡ đảo: §a%sizeisland"
            - "§c"
            - "§aLevel: §b%mylevel §a(%xplevel/§c%xpneed§a)"
            - "§a"
            - "§efoxcraft.zapto.org"      
ScoreBoardPrivate:                      
    1:
        world: "world"
        title: "§l§eSCOREBOARD"    
        score:    
            - " §bYour Coins: %getcoins"
            - " §1 Line 2"
            - " §e Line 3"