name: DangnhapOP
main: KhoaGamingPro\DangnhapOP\Main
author: KhoaGamingPro
description: Đăng nhập dành cho OP, tránh hacker
version: 1.0
api: [3.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
commands:
    dnop:
      description: Chỉ đăng nhập dành cho OP
      aliases: [dangnhapop]