---
# Available tags for broadcast messages, popups and titles:
# - {MAXPLAYERS}: Show maximum players by server 
# - {TOTALPLAYERS}: Show the number of all online players
# - {PREFIX}: Show prefix
# - {TIME}: Show current time
# - {TODAY}: Show current day and moth
# sendTitle
sendTitle: 
    enable: false 
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
                  #  [ Title,  SubTitle ]
        ["{PREFIX} &b1. This is message!", "{TIME}"],
        ["{PREFIX} &b2. This is message!", "{TIME}"],
        ["{PREFIX} &b3. This is message!", "{TIME}"]
    ]
# sendPopup
sendPopup: 
    enable: false
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
        "{TODAY} {PREFIX} &b1. This is message!",
        "{TODAY} {PREFIX} &b2. This is message!",
        "{TODAY} {PREFIX} &b3. This is message!"
    ]
# sendTips
sendTips: 
    enable: false
         # Time count down 
    timeCountDown: 20    
         # Messages
    Messages: [
        "{TODAY} {PREFIX} &b1. This is message!",
        "{TODAY} {PREFIX} &b2. This is message!",
        "{TODAY} {PREFIX} &b3. This is message!"
    ]
# sendAlerts
sendAlerts: 
    enable: true
         # Time count down 
    timeCountDown: 50    
         # Messages
    Messages: [
        "{PREFIX} &l&bBất kỳ bạn ở đâu sẽ có mobs spawn xung quanh, hãy cẩn thận nếu trời tối!",
        "{PREFIX} &l&bNếu bạn thấy server hay, hãy ủng hộ server có thêm kinh phí duy trì bằng cách &a/napthe &bnhé",
        "{PREFIX} &l&aNếu bạn đang bế tắc trong việc chế tạo các món vật phẩm mới hãy &c/recipe &ahoặc mua một &bAdvanced Crafting Table",
        "{PREFIX} &l&aBạn đang chơi trên server &efoxcraft.zapto.org",
        "{PREFIX} &l&cHãy lưu ý nếu bạn đang nạp thẻ cần ghi đúng giá của thẻ cào và nhà mạng nhé!",
        "{PREFIX} &l&aCảm ơn bạn đã ủng hộ server!",
        "{PREFIX} &l&bNếu bạn có ý kiến trong việc gì, hãy nhắn qua facebook: &chttps://www.facebook.com/Nam0981/",
        "{PREFIX}&l&bĐi Dungeon sẽ giúp bạn lên level nhanh hơn!"
    ]
...